name: Generate Snake Game

on:
  schedule:
    # Cada día a las 00:00
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate snake
        uses: d3v4k0/generate-snake-game-from-github-contribution-grid@main
        with:
          github_username: MatiDroid12 # Reemplaza con tu nombre de usuario
          # Optional:
          # width: 600 # Define el ancho de la imagen
          # height: 250 # Define la altura de la imagen
          # color: "#3498db" # Define el color de la serpiente (ej: azul claro)
          # background_color: "#2c3e50" # Define el color de fondo (ej: gris oscuro)
          # speed: 10 # Define la velocidad de la animación (ej: 10)
          # output_format: gif # Define el formato de salida (ej: gif o svg)
      - name: Commit and push
        run: |
          git config --local user.email "matias.chavez711@gmail.com"
          git config --local user.name "MatiDroid12"
          git add .
          git commit -m "Update snake" || true
          git push origin HEAD
