name: Generate Space Shooter Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Cada 12 horas
  workflow_dispatch: # Permite ejecución manual
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate space shooter
        uses: czl9707/gh-space-shooter@v1.0.0
        with:
          github_user_name: MatiDroid21
          
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update space shooter animation" || exit 0
          git push
